导入代码所需库

In [21]:
import pandas as pd
import numpy as np
import random
from matplotlib import pyplot as plt

计算点与簇中心的欧氏距离：

In [22]:
def calculate_distance(x, y):
    distance = np.linalg.norm(x - y)
    return distance

K-means类的封装

包含文件读取、数据切分、更新簇中心、分类主函数

In [23]:
class KMeans:
    def __init__(self, n_clusters=3, max_iter=100):
        self.data = None
        self.n_clusters = n_clusters
        self.max_iter = max_iter
        self.X = None
        self.Y = None

    def read_data(self, filename="./iris_data/iris.csv"):
        self.data = pd.read_csv(filename)
        self.X, self.Y = self.data.iloc[:, 1: -1], self.data.iloc[:, -1]
        self.X = self.X.values

    def get_clusters(self, clusters_center):
        distances = np.linalg.norm(self.X[:, np.newaxis] - clusters_center, axis=2)
        new_clusters = np.argmin(distances, axis=1)
        return new_clusters

    def update_clusters(self, new_clusters):
        new_center = []
        for i in range(self.n_clusters):
            sum = np.zeros(self.X.shape[1])
            cnt = 0
            for j in range(self.X.shape[0]):
                if new_clusters[j] == i:
                    cnt += 1
                    sum += self.X[j]
            mean = sum / cnt
            new_center.append(mean)
        new_center = np.array(new_center)
        return new_center

    def classify(self):
        clusters_center = np.array(random.sample(self.X.tolist(), self.n_clusters))
        for _ in range(self.max_iter):
            new_clusters = self.get_clusters(clusters_center)
            clusters_center = self.update_clusters(new_clusters)
            print(clusters_center)

        return clusters_center

    def evaluate(self):
        clusters_center = self.classify()
        classify_distance = self.get_clusters(clusters_center)

        iris_dataset = self.data.iloc[:, 1:].to_numpy()
        print(clusters_center)

主函数

In [24]:
if __name__ == '__main__':
    kmeans = KMeans()
    kmeans.read_data()
    kmeans.classify()
    kmeans.evaluate()

[[6.61578947 2.99824561 5.46842105 1.96666667]
 [5.79302326 2.70465116 4.16046512 1.29069767]
 [5.006      3.428      1.462      0.246     ]]
[[6.67735849 3.00754717 5.51320755 1.97169811]
 [5.79361702 2.71914894 4.2212766  1.34255319]
 [5.006      3.428      1.462      0.246     ]]
[[6.702 3.016 5.556 1.992]
 [5.822 2.728 4.256 1.36 ]
 [5.006 3.428 1.462 0.246]]
[[6.76956522 3.03695652 5.6        2.00869565]
 [5.82962963 2.73148148 4.31481481 1.39259259]
 [5.006      3.428      1.462      0.246     ]]
[[6.80232558 3.04418605 5.64883721 2.03023256]
 [5.85438596 2.74210526 4.34561404 1.40877193]
 [5.006      3.428      1.462      0.246     ]]
[[6.8275     3.07       5.7        2.0625    ]
 [5.885      2.74       4.37666667 1.41833333]
 [5.006      3.428      1.462      0.246     ]]
[[6.85384615 3.07692308 5.71538462 2.05384615]
 [5.88360656 2.74098361 4.38852459 1.43442623]
 [5.006      3.428      1.462      0.246     ]]
[[6.85384615 3.07692308 5.71538462 2.05384615]
 [5.88360656 2.7409